apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: formazione-oc
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi

