apiVersion: v1
kind: Pod
metadata:
  name: small-pod
  namespace: formazione-oc
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        memory: "256Mi"
        cpu: "250m"
      limits:
        memory: "512Mi"
        cpu: "500m"

